### ISSUE TITLE
Add ability to prefix metrics with custom prefix

### ISSUE THREAD

**Issue by cmeissner** [codeaffen/p3exporter-fritzbox-smarthome#5]
**Is your feature request related to a problem? Please describe.**

At the moment all metrics from this collector are prefixed with `p3e_fb` e.g.

```
# HELP p3e_fb_battery_status Battery level and status
# TYPE p3e_fb_battery_status gauge
p3e_fb_battery_status{ain="11959 0380848",battery_low="False",device="Badezimmer"} 50.0
```

It would be a good idea to make this prefix configurable to be able to have more than one exporter with this collector being collected from a single prometheus instance.

**Describe the solution you'd like**

There should be an optional parameter `prefix` within the configuration as followed:

```yaml
collectors:
  - p3eFritzBox.collector.smarthome
collector_opts:
  thermostat:
    username: smarthome
    password: v3rys3cr3t
    prefix: daves_fb
```

Within this code https://github.com/codeaffen/p3exporter-fritzbox-smarthome/blob/916a3af4b0a58436e4816804766596a75bc79103/p3eFritzBox/collector/smarthome.py#L18-L22

the parameter is requested but defaulted to `p3e_fb` if it is not set:

```python
self.prefix = self.opts.pop("prefix", "p3e_fb")
``` 
 
**Additional context**

As the parameter is defaulted this feature shouldn't be a breaking one.
