### ISSUE TITLE
Allow configuration of more than one FritzBox

### ISSUE THREAD

**Issue by cmeissner** [codeaffen/p3exporter-fritzbox-smarthome#6]
**Is your feature request related to a problem? Please describe.**

Currently it is possible to configure one Fritzbox only. Some user can have the demand of configuring more than one Fritzbox at a time.

**Describe the solution you'd like**

The connection parameters should be moved in a list of dicts for each Fritzbox. It should also be possible to configure default parameters on a upper level, e.g.

```yaml
collector_opts:
  smarthome:
    defaults:
        username: smarthome
        password: v3rys3cr3t
        ssl_verify: false
    devices:
        - name: "Fritz at home"
          username: mySmartHomeUser
          password: sm4rth0m3
        - name: "Fritz at cottage"
          username: cottageUser
          password: c0tt4g3p455
          hostname: https://cottage.fritzbox.example.com
```

In `defaults` dict you can pass defaults for all entries in `devices` list and override defaults defined in code. Parameters in device entries which are neither provided in defaults nor in entry itself will be use defaults in code. 

**Additional context**

It would be good to have the feature request #5 is already implemented to provide a `prefix` parameter for each entry also to have the ability to differentiate each Fritzbox data.
